# Generated by Django 5.0.2 on 2025-12-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='idx_student_created_at'),
        ),
    ]
