# Generated by Django 5.0.2 on 2025-12-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher_profile_picture_teacher_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(db_index=True, help_text='Grade level (e.g., Grade 11, Grade 12)', max_length=20)),
                ('strand', models.CharField(db_index=True, help_text='Academic strand (e.g., HUMSS, GAS, ABM, Cookery, SMAW)', max_length=50)),
                ('section', models.CharField(help_text='Section name (e.g., A, B, Einstein, Newton)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'users_class',
                'ordering': ['grade_level', 'strand', 'section'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='class_assigned',
            field=models.ForeignKey(blank=True, help_text='Class to which the student is assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.class'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_assigned'], name='idx_student_class'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['teacher'], name='idx_class_teacher'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['grade_level'], name='idx_class_grade'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['strand'], name='idx_class_strand'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['grade_level', 'strand', 'section'], name='idx_class_grade_strand_sec'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('teacher', 'grade_level', 'strand', 'section')},
        ),
    ]
