# Generated by Django 4.2.27 on 2026-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_api_key', models.CharField(blank=True, default='', max_length=500)),
                ('ai_base_url', models.CharField(blank=True, default='https://openrouter.ai/api/v1', max_length=255)),
                ('ai_model', models.CharField(blank=True, default='meta-llama/llama-3.1-8b-instruct:free', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
