# Generated by Django 4.2.30 on 2026-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default="We're performing scheduled maintenance. The system will be back online shortly. Thank you for your patience.", help_text='Custom message shown on the maintenance page.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='When enabled, non-superadmin users see the maintenance page instead of the app.'),
        ),
    ]
