# Generated by Django 4.2.30 on 2026-06-09 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('topic', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('type_counts', models.JSONField(default=dict)),
                ('total_requested', models.IntegerField(default=0)),
                ('total_generated', models.IntegerField(default=0)),
                ('questions_by_type', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exams_ai_generation_task',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Subject of the exam (e.g., English, Physical Science, Filipino)', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(help_text='Duration of the exam in minutes')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the exam is visible to students')),
                ('questionnaire_file', models.FileField(blank=True, help_text='Upload test questionnaire document (PDF, DOCX) for automatic question extraction', null=True, upload_to='exam_questionnaires/')),
                ('answer_key_file', models.FileField(blank=True, help_text='Upload answer key document (PDF, DOCX, TXT) for automatic answer extraction', null=True, upload_to='exam_answer_keys/')),
                ('auto_extracted', models.BooleanField(default=False, help_text='Whether questions were automatically extracted from uploaded files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams_exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Class Assignment',
                'verbose_name_plural': 'Exam Class Assignments',
                'db_table': 'exams_class_assignment',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('IDENTIFICATION', 'Identification'), ('ENUMERATION', 'Enumeration'), ('ESSAY', 'Essay'), ('TRUE_FALSE', 'True/False')], db_index=True, max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, help_text="JSON field for MCQ options: [{'key': 'A', 'value': 'Option text'}]", null=True)),
                ('correct_answer', models.JSONField(help_text='JSON field for correct answer(s). Format varies by question type.')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order_index', models.IntegerField(default=0, help_text='Order of the question in the exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'exams_question',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemAnalysisAIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.JSONField(default=dict)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_result', to='exams.exam')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_item_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams_item_analysis_ai_result',
            },
        ),
        migrations.CreateModel(
            name='ExamStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Exam Student Assignment',
                'verbose_name_plural': 'Exam Student Assignments',
                'db_table': 'exams_student_assignment',
            },
        ),
    ]
