# Generated by Django 5.0.2 on 2025-12-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(help_text='Duration of the exam in minutes')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether the exam is visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams_exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('IDENTIFICATION', 'Identification'), ('ENUMERATION', 'Enumeration'), ('ESSAY', 'Essay'), ('TRUE_FALSE', 'True/False')], db_index=True, max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, help_text="JSON field for MCQ options: [{'key': 'A', 'value': 'Option text'}]", null=True)),
                ('correct_answer', models.JSONField(help_text='JSON field for correct answer(s). Format varies by question type.')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order_index', models.IntegerField(default=0, help_text='Order of the question in the exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'exams_question',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active'], name='idx_exam_active'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by'], name='idx_exam_created_by'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam'], name='idx_question_exam'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='idx_question_type'),
        ),
    ]
