# Generated by Django 5.0.2 on 2025-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active', 'created_by'], name='idx_exam_active_teacher'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['-created_at'], name='idx_exam_created_desc'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order_index'], name='idx_question_exam_order'),
        ),
    ]
