# Generated by Django 4.2.30 on 2026-06-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstudentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='users.student'),
        ),
        migrations.AddField(
            model_name='examclassassignment',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='users.class'),
        ),
        migrations.AddField(
            model_name='examclassassignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='quarter',
            field=models.ForeignKey(blank=True, help_text='Quarter when the exam is created or administered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='users.quarter'),
        ),
        migrations.AddField(
            model_name='aigenerationtask',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='exams.exam'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam'], name='idx_question_exam'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='idx_question_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order_index'], name='idx_question_exam_order'),
        ),
        migrations.AddIndex(
            model_name='examstudentassignment',
            index=models.Index(fields=['exam'], name='idx_exam_student_exam'),
        ),
        migrations.AddIndex(
            model_name='examstudentassignment',
            index=models.Index(fields=['student'], name='idx_exam_student_student'),
        ),
        migrations.AddIndex(
            model_name='examstudentassignment',
            index=models.Index(fields=['exam', 'student'], name='idx_exam_student_composite'),
        ),
        migrations.AlterUniqueTogether(
            name='examstudentassignment',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='examclassassignment',
            index=models.Index(fields=['exam'], name='idx_exam_class_exam'),
        ),
        migrations.AddIndex(
            model_name='examclassassignment',
            index=models.Index(fields=['class_assigned'], name='idx_exam_class_class'),
        ),
        migrations.AlterUniqueTogether(
            name='examclassassignment',
            unique_together={('exam', 'class_assigned')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active'], name='idx_exam_active'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by'], name='idx_exam_created_by'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active', 'created_by'], name='idx_exam_active_teacher'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['-created_at'], name='idx_exam_created_desc'),
        ),
    ]
