# Generated by Django 5.0.2 on 2025-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_idx_exam_active_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answer_key_file',
            field=models.FileField(blank=True, help_text='Upload answer key document (PDF, DOCX, TXT) for automatic answer extraction', null=True, upload_to='exam_answer_keys/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='auto_extracted',
            field=models.BooleanField(default=False, help_text='Whether questions were automatically extracted from uploaded files'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questionnaire_file',
            field=models.FileField(blank=True, help_text='Upload test questionnaire document (PDF, DOCX) for automatic question extraction', null=True, upload_to='exam_questionnaires/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject of the exam (e.g., English, Physical Science, Filipino)', max_length=100, null=True),
        ),
    ]
