# Generated by Django 5.0.2 on 2025-12-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_answer_key_file_exam_auto_extracted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Whether questions were generated using AI'),
        ),
        migrations.AddField(
            model_name='exam',
            name='ai_generation_params',
            field=models.JSONField(blank=True, help_text='Parameters used for AI generation (topic, difficulty, question types, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='ai_model_used',
            field=models.CharField(blank=True, help_text='Name of the AI model used for question generation (e.g., llama3.2)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='generation_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when AI generation was completed', null=True),
        ),
    ]
