# Generated by Django 5.0.2 on 2025-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_ai_generated_exam_ai_generation_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Whether this question was generated using AI'),
        ),
    ]
