# Generated by Django 5.0.2 on 2025-12-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_add_ai_generated_to_question'),
        ('users', '0004_class_student_class_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='users.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Exam Class Assignment',
                'verbose_name_plural': 'Exam Class Assignments',
                'db_table': 'exams_class_assignment',
                'indexes': [models.Index(fields=['exam'], name='idx_exam_class_exam'), models.Index(fields=['class_assigned'], name='idx_exam_class_class')],
                'unique_together': {('exam', 'class_assigned')},
            },
        ),
    ]
