# Generated by Django 5.0.2 on 2025-12-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examclassassignment'),
        ('users', '0004_class_student_class_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='users.student')),
            ],
            options={
                'verbose_name': 'Exam Student Assignment',
                'verbose_name_plural': 'Exam Student Assignments',
                'db_table': 'exams_student_assignment',
                'indexes': [models.Index(fields=['exam'], name='idx_exam_student_exam'), models.Index(fields=['student'], name='idx_exam_student_student'), models.Index(fields=['exam', 'student'], name='idx_exam_student_composite')],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
