# Generated by Django 5.0.2 on 2025-12-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_add_exam_student_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='ai_generation_params',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='ai_model_used',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='generation_timestamp',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ai_generated',
        ),
    ]
