# Generated by Django 4.2.27 on 2026-05-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_exam_ai_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('topic', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('type_counts', models.JSONField(default=dict)),
                ('total_requested', models.IntegerField(default=0)),
                ('total_generated', models.IntegerField(default=0)),
                ('questions_by_type', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='exams.exam')),
            ],
            options={
                'db_table': 'exams_ai_generation_task',
            },
        ),
    ]
