# Generated by Django 4.2.30 on 2026-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_ai_generation_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the exam is visible to students'),
        ),
    ]
