# Generated by Django 4.2.30 on 2026-05-31 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_quarter'),
        ('exams', '0010_alter_exam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='quarter',
            field=models.ForeignKey(blank=True, help_text='Quarter when the exam is created or administered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='users.quarter'),
        ),
    ]
