# Generated by Django 4.2.30 on 2026-06-02 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0011_exam_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAnalysisAIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.JSONField(default=dict)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_result', to='exams.exam')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_item_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams_item_analysis_ai_result',
            },
        ),
    ]
