"""
Django settings for exam_system project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/

LOCAL NETWORK CONFIGURATION (Requirement 18):
This application is designed to run on a local network without internet connectivity.
- The Django server runs on the teacher's laptop (0.0.0.0:8000)
- Students connect via WiFi hotspot created by the teacher's laptop
- All data is stored locally in MySQL database on the teacher's laptop
- No external services or APIs are used
- Static files are served directly from the local server
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-81fqzw3gj57cl4=-a-k6__e#b4d2g5*$@j0xz7twzx1-4@d!%d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes', 'on')

# Local Network Configuration (Requirement 18.1, 18.2, 18.5)
# Allow access from local network for offline exam system
# The wildcard '*' allows any IP address on the local network to connect
# This is safe for local network deployment without internet connectivity
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '*',  # Allows all local network IP addresses (192.168.x.x, 10.x.x.x, etc.)
]

# Django Debug Toolbar Configuration
# Show toolbar for localhost and 127.0.0.1
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Debug toolbar
    'debug_toolbar',
    # Tailwind CSS (Requirement 17.1, 18.4)
    'tailwind',
    'theme',
    # PWA
    'pwa',
    # Custom apps
    'users',
    'exams',
    'attempts',
    'uploads',
    'exam_system',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # Debug toolbar
    'exam_system.middleware.FirstTimeSetupMiddleware',  # First-time setup redirect
    'exam_system.middleware.FileSizeValidationMiddleware',  # File upload validation (Requirements 4.3, 13.1)
]

ROOT_URLCONF = 'exam_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.navbar_context',  # Navbar context (Requirements 1.3, 1.4)
            ],
        },
    },
]

WSGI_APPLICATION = 'exam_system.wsgi.application'


# Database Configuration (Requirement 18.3, 18.4)
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# MySQL runs locally on teacher's laptop for offline LAN usage.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'exam_system_db'),
        'USER': os.getenv('DB_USER', 'exam_admin'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        # Connection pooling settings (Requirement 9.5)
        # Django's persistent connections feature reuses database connections
        # Set to 600 seconds (10 minutes) to keep connections alive during exam sessions
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static Files Configuration (Requirement 18.1, 18.2)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# All static files are served locally from teacher's laptop
# No CDN or external static file services are used
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Tailwind CSS Configuration (Requirement 17.1, 18.4)
# Django-tailwind generates CSS locally for offline operation
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = r'C:\Program Files\nodejs\npm.cmd'

# Media Files Configuration (Requirement 18.4)
# Uploaded documents are stored locally on teacher's laptop
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# SECURITY CONFIGURATION (Requirement 1.4)
# ============================================

# Session Security Configuration
# Protects session cookies from XSS and CSRF attacks
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 7200  # 2 hours - sufficient for exam duration
SESSION_SAVE_EVERY_REQUEST = True  # Preserve exam state on every request

# Session Cookie Security (Requirement 1.4)
# HttpOnly: Prevents JavaScript access to session cookies (XSS protection)
# SameSite: Prevents CSRF attacks by restricting cross-site cookie sending
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS attacks on session cookies
SESSION_COOKIE_SAMESITE = 'Strict'  # Strict CSRF protection for local network
SESSION_COOKIE_SECURE = False  # Set to False for local network (no HTTPS)
SESSION_COOKIE_NAME = 'exam_sessionid'  # Custom name to avoid fingerprinting

# CSRF Protection (Requirement 1.4)
# Django CSRF middleware is enabled in MIDDLEWARE list above
# Additional CSRF cookie security settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for AJAX requests
CSRF_COOKIE_SAMESITE = 'Strict'  # Strict CSRF protection
CSRF_COOKIE_SECURE = False  # Set to False for local network (no HTTPS)
CSRF_COOKIE_NAME = 'exam_csrftoken'  # Custom name to avoid fingerprinting
CSRF_USE_SESSIONS = False  # Store CSRF token in cookie (not session)
CSRF_COOKIE_AGE = 7200  # Match session age
CSRF_TRUSTED_ORIGINS = [
    'https://valuateai.onrender.com',
    'https://www.valuateai.onrender.com',
    'https://valuateai.onrender.com',
]

# XSS Prevention (Requirement 1.4)
# Django templates have auto-escaping enabled by default
# Additional XSS protection headers
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing

# Clickjacking Protection
X_FRAME_OPTIONS = 'DENY'  # Prevent site from being embedded in frames

# Additional Security Headers
# These provide defense-in-depth for local network deployment
SECURE_REFERRER_POLICY = 'same-origin'  # Only send referrer to same origin

# Password Security (Requirement 1.4)
# Strong password hashing using PBKDF2 with SHA256
# Django's default password validators are configured above in AUTH_PASSWORD_VALIDATORS
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # Default, secure
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Most secure if argon2-cffi installed
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',  # Secure if bcrypt installed
]

# File Upload Security (Requirement 1.4, 3.4)
# Maximum upload size: 50 MB (prevents DoS via large file uploads)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB in bytes

# Allowed file upload extensions (enforced in UploadService)
FILE_UPLOAD_ALLOWED_EXTENSIONS = ['.pdf', '.docx']

# File upload directory permissions
FILE_UPLOAD_PERMISSIONS = 0o644  # Read/write for owner, read for others
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # Full access for owner, read/execute for others

# Profile Picture Upload Configuration (Requirements 4.2, 4.3, 4.4, 13.1)
# Maximum profile picture size: 5 MB
PROFILE_PICTURE_MAX_SIZE = 5 * 1024 * 1024  # 5 MB in bytes

# Allowed profile picture formats
PROFILE_PICTURE_ALLOWED_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
PROFILE_PICTURE_ALLOWED_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif']

# Image compression settings
PROFILE_PICTURE_MAX_WIDTH = 800  # Maximum width in pixels
PROFILE_PICTURE_MAX_HEIGHT = 800  # Maximum height in pixels
PROFILE_PICTURE_JPEG_QUALITY = 85  # JPEG compression quality (0-100)

# Local Network Deployment Configuration (Requirement 18.4, 18.5)
# Ensure no external service dependencies
# All services run locally on teacher's laptop:
# - Django application server (0.0.0.0:8000)
# - MySQL database (localhost:3306)
# - Static file serving (local filesystem)
# - Media file storage (local filesystem)
# - Session storage (database backend)
# No external APIs, CDNs, or cloud services are used

# Cache Configuration (Requirements 11.1, 11.5)
# Use database-backed caching for dashboard metrics and score trends
# Database cache is suitable for local network deployment without external dependencies
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Limit cache size
            'CULL_FREQUENCY': 3,  # Remove 1/3 of entries when MAX_ENTRIES is reached
        },
        'TIMEOUT': 300,  # Default timeout: 5 minutes
    }
}

# Cache key prefixes for different data types
CACHE_KEY_DASHBOARD_METRICS = 'dashboard_metrics_{student_id}'
CACHE_KEY_SCORE_TREND = 'score_trend_{student_id}'
CACHE_KEY_TYPE_PERFORMANCE = 'type_performance_{student_id}'

# Cache timeouts (in seconds)
CACHE_TIMEOUT_DASHBOARD_METRICS = 300  # 5 minutes
CACHE_TIMEOUT_SCORE_TREND = 600  # 10 minutes
CACHE_TIMEOUT_TYPE_PERFORMANCE = 300  # 5 minutes

# ============================================
# LOGGING CONFIGURATION
# ============================================

# Logging Configuration (Requirement 3.3)
# Configure logging for debugging and monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module} {funcName} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'exam_system.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'service_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'services.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'services': {
            'handlers': ['console', 'service_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'processing': {
            'handlers': ['console', 'service_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'repositories': {
            'handlers': ['service_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file', 'error_file'],
        'level': 'INFO',
    },
}

# ============================================
# PWA CONFIGURATION
# ============================================

PWA_APP_NAME = 'ValuateAI'
PWA_APP_DESCRIPTION = 'AI-powered exam system for students and teachers'
PWA_APP_THEME_COLOR = '#2563eb'
PWA_APP_BACKGROUND_COLOR = '#f9fafb'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/img/icons/icon-72x72.png',
        'sizes': '72x72'
    },
    {
        'src': '/static/img/icons/icon-96x96.png',
        'sizes': '96x96'
    },
    {
        'src': '/static/img/icons/icon-128x128.png',
        'sizes': '128x128'
    },
    {
        'src': '/static/img/icons/icon-144x144.png',
        'sizes': '144x144'
    },
    {
        'src': '/static/img/icons/icon-152x152.png',
        'sizes': '152x152'
    },
    {
        'src': '/static/img/icons/icon-192x192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/img/icons/icon-384x384.png',
        'sizes': '384x384'
    },
    {
        'src': '/static/img/icons/icon-512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/icons/icon-152x152.png',
        'sizes': '152x152'
    },
    {
        'src': '/static/img/icons/icon-192x192.png',
        'sizes': '192x192'
    }
]
PWA_APP_SPLASH_SCREEN = []
PWA_SERVICE_WORKER_PATH = BASE_DIR / 'static' / 'js' / 'serviceworker.js'
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
