from django.urls import path
from .views_school_admin import (
    SchoolAdminDashboardView,
    SchoolAdminTeachersView,
    SchoolAdminCreateTeacherView,
    SchoolAdminEditTeacherView,
    SchoolAdminTeacherDetailView,
    SchoolAdminToggleTeacherActiveView,
    SchoolAdminStudentsView,
    SchoolAdminStudentDetailView,
    SchoolAdminResetPasswordView,
    SchoolAdminDeleteUserView,
    SchoolAdminClassesView,
    SchoolAdminCreateClassView,
    SchoolAdminEditClassView,
    SchoolAdminDeleteClassView,
    SchoolAdminClassDetailView,
    SchoolAdminLookupsView,
    SchoolAdminStudentAssignView,
    SchoolAdminBulkStudentAssignView,
)

urlpatterns = [
    path('dashboard/', SchoolAdminDashboardView.as_view(), name='school_admin_dashboard'),
    path('teachers/', SchoolAdminTeachersView.as_view(), name='school_admin_teachers'),
    path('teachers/create/', SchoolAdminCreateTeacherView.as_view(), name='school_admin_create_teacher'),
    path('teachers/<int:teacher_id>/', SchoolAdminTeacherDetailView.as_view(), name='school_admin_teacher_detail'),
    path('teachers/<int:teacher_id>/edit/', SchoolAdminEditTeacherView.as_view(), name='school_admin_edit_teacher'),
    path('teachers/<int:teacher_id>/toggle-active/', SchoolAdminToggleTeacherActiveView.as_view(), name='school_admin_toggle_teacher_active'),
    path('students/', SchoolAdminStudentsView.as_view(), name='school_admin_students'),
    path('students/<int:student_id>/', SchoolAdminStudentDetailView.as_view(), name='school_admin_student_detail'),
    path('reset-password/', SchoolAdminResetPasswordView.as_view(), name='school_admin_reset_password'),
    path('delete-user/', SchoolAdminDeleteUserView.as_view(), name='school_admin_delete_student'),
    path('classes/', SchoolAdminClassesView.as_view(), name='school_admin_classes'),
    path('classes/create/', SchoolAdminCreateClassView.as_view(), name='school_admin_create_class'),
    path('classes/<int:class_id>/', SchoolAdminClassDetailView.as_view(), name='school_admin_class_detail'),
    path('classes/<int:class_id>/edit/', SchoolAdminEditClassView.as_view(), name='school_admin_edit_class'),
    path('classes/<int:class_id>/delete/', SchoolAdminDeleteClassView.as_view(), name='school_admin_delete_class'),
    path('lookups/', SchoolAdminLookupsView.as_view(), name='school_admin_lookups'),
    path('students/assign/', SchoolAdminStudentAssignView.as_view(), name='school_admin_student_assign'),
    path('students/bulk-assign/', SchoolAdminBulkStudentAssignView.as_view(), name='school_admin_bulk_assign'),
    path('students/bulk-assign/<int:class_id>/', SchoolAdminBulkStudentAssignView.as_view(), name='school_admin_bulk_assign_class'),
]
