# Generated by Django 4.2.30 on 2026-06-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.JSONField(help_text='JSON field for answer data. Format varies by question type.')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('teacher_feedback', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'attempts_answer',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], db_index=True, default='in_progress', max_length=20)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for potential cheating')),
                ('flag_reason', models.CharField(blank=True, help_text="Reason for flagging (e.g., 'Auto-submitted after 4 tab switches')", max_length=255)),
                ('auto_submitted', models.BooleanField(default=False, help_text='Whether exam was auto-submitted due to violations')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'db_table': 'attempts_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TabViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violated_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration away from exam in seconds', null=True)),
                ('warning_number', models.IntegerField(help_text='Which warning this violation triggered (1-3)')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_violations', to='attempts.attempt')),
            ],
            options={
                'verbose_name': 'Tab Violation',
                'verbose_name_plural': 'Tab Violations',
                'db_table': 'attempts_tab_violation',
                'ordering': ['violated_at'],
            },
        ),
    ]
