# Generated by Django 5.0.2 on 2025-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='idx_answer_attempt_quest'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['graded_at'], name='idx_answer_graded_at'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'exam'], name='idx_attempt_student_exam'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status', '-submitted_at'], name='idx_attempt_status_submit'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['-submitted_at'], name='idx_attempt_submit_desc'),
        ),
    ]
