# Generated by Django 4.2.30 on 2026-06-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('attempts', '0002_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.attempt'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question'),
        ),
        migrations.AddIndex(
            model_name='tabviolation',
            index=models.Index(fields=['attempt', 'violated_at'], name='idx_tabviol_attempt_time'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student'], name='idx_attempt_student'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam'], name='idx_attempt_exam'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status'], name='idx_attempt_status'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'exam'], name='idx_attempt_student_exam'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status', '-submitted_at'], name='idx_attempt_status_submit'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['-submitted_at'], name='idx_attempt_submit_desc'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'submitted_at'], name='idx_attempt_student_submit'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt'], name='idx_answer_attempt'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='idx_answer_question'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='idx_answer_attempt_quest'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['graded_at'], name='idx_answer_graded_at'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
