# Generated by Django 5.0.2 on 2025-12-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_answer_idx_answer_attempt_quest_and_more'),
        ('exams', '0002_exam_idx_exam_active_teacher_and_more'),
        ('users', '0002_student_bio_student_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'submitted_at'], name='idx_attempt_student_submit'),
        ),
    ]
