# Generated by Django 5.0.2 on 2025-12-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_add_student_submitted_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='auto_submitted',
            field=models.BooleanField(default=False, help_text='Whether exam was auto-submitted due to violations'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='flag_reason',
            field=models.CharField(blank=True, help_text="Reason for flagging (e.g., 'Auto-submitted after 4 tab switches')", max_length=255),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for potential cheating'),
        ),
        migrations.CreateModel(
            name='TabViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violated_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration away from exam in seconds', null=True)),
                ('warning_number', models.IntegerField(help_text='Which warning this violation triggered (1-3)')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_violations', to='attempts.attempt')),
            ],
            options={
                'verbose_name': 'Tab Violation',
                'verbose_name_plural': 'Tab Violations',
                'db_table': 'attempts_tab_violation',
                'ordering': ['violated_at'],
                'indexes': [models.Index(fields=['attempt', 'violated_at'], name='idx_tabviol_attempt_time')],
            },
        ),
    ]
