# Generated by Django 5.0.2 on 2025-12-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the uploaded file', max_length=500)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOCX', 'Word Document')], help_text='Type of uploaded document (PDF or DOCX)', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when document was uploaded')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current processing status of the document', max_length=20)),
                ('uploaded_by', models.ForeignKey(help_text='Teacher who uploaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Uploaded Document',
                'verbose_name_plural': 'Uploaded Documents',
                'db_table': 'uploads_uploadeddocument',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Raw text extracted from the document')),
                ('processed_questions', models.JSONField(default=list, help_text='JSON array of extracted/generated questions')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when content was extracted')),
                ('document', models.OneToOneField(help_text='Source document for this extracted content', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_content', to='uploads.uploadeddocument')),
            ],
            options={
                'verbose_name': 'Extracted Content',
                'verbose_name_plural': 'Extracted Contents',
                'db_table': 'uploads_extractedcontent',
            },
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['uploaded_by'], name='idx_uploaded_by'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['processing_status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='extractedcontent',
            index=models.Index(fields=['document'], name='idx_document'),
        ),
    ]
