# Generated by Django 4.2.30 on 2026-06-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Teacher who uploaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='extractedcontent',
            name='document',
            field=models.OneToOneField(help_text='Source document for this extracted content', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_content', to='uploads.uploadeddocument'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['uploaded_by'], name='idx_uploaded_by'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['processing_status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['uploaded_by', 'processing_status'], name='idx_upload_teacher_status'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['-uploaded_at'], name='idx_upload_date_desc'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['file_type'], name='idx_upload_file_type'),
        ),
        migrations.AddIndex(
            model_name='extractedcontent',
            index=models.Index(fields=['document'], name='idx_document'),
        ),
    ]
