# Generated by Django 5.0.2 on 2025-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['uploaded_by', 'processing_status'], name='idx_upload_teacher_status'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['-uploaded_at'], name='idx_upload_date_desc'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['file_type'], name='idx_upload_file_type'),
        ),
    ]
